/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import SportPlanner.SportPlanner;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


/** 
 *
 * @author Ciccio
 */
public class InserisciNuovoTorneoGUI extends javax.swing.JFrame {
    private SportPlanner sportPlanner;
    private ArrayList<LocalTime> orari = new ArrayList<>();
    /** Creates new form InserisciNuovoTorneo */
    public InserisciNuovoTorneoGUI(SportPlanner sp) {
        this.sportPlanner = sp;
        initComponents(); 
        scegliCampi.setEnabled(false);
        inserisciTorneo.setEnabled(true);
        setVisible(true);
        jLabel5.setVisible(false);
        pack();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IdTorneo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numPartecipanti = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        prezzo = new javax.swing.JTextField();
        scegliCampi = new javax.swing.JButton();
        inserisciTorneo = new javax.swing.JButton();
        giorno = new javax.swing.JTextField();
        mese = new javax.swing.JTextField();
        anno = new javax.swing.JTextField();
        giorno1 = new javax.swing.JTextField();
        mese1 = new javax.swing.JTextField();
        anno1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        jLabel1.setText("SportPlanner");

        jLabel2.setText("Identificativo");

        IdTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTorneoActionPerformed(evt);
            }
        });

        jLabel3.setText("Scegli la data di inizio:");

        jLabel4.setText("Scegli la data di fine:");

        numPartecipanti.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "10", "12", "14", "16", "18", "20" }));
        numPartecipanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPartecipantiActionPerformed(evt);
            }
        });

        jLabel6.setText("Inserisci il numero di squadre: ");
        jLabel6.setToolTipText("");

        jLabel7.setText("Inserisci il prezzo di iscrizione: ");

        scegliCampi.setText("Scegli campi");
        scegliCampi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scegliCampiActionPerformed(evt);
            }
        });

        inserisciTorneo.setText("Inserisci torneo");
        inserisciTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserisciTorneoActionPerformed(evt);
            }
        });

        giorno.setForeground(new java.awt.Color(164, 164, 164));
        giorno.setText("Giorno");
        giorno.setToolTipText("");
        giorno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                giornoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                giornoFocusLost(evt);
            }
        });

        mese.setForeground(new java.awt.Color(164, 164, 164));
        mese.setText("Mese");
        mese.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                meseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                meseFocusLost(evt);
            }
        });

        anno.setForeground(new java.awt.Color(164, 164, 164));
        anno.setText("Anno");
        anno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                annoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                annoFocusLost(evt);
            }
        });

        giorno1.setForeground(new java.awt.Color(164, 164, 164));
        giorno1.setText("Giorno");
        giorno1.setToolTipText("");
        giorno1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                giorno1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                giorno1FocusLost(evt);
            }
        });

        mese1.setForeground(new java.awt.Color(164, 164, 164));
        mese1.setText("Mese");
        mese1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mese1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mese1FocusLost(evt);
            }
        });

        anno1.setForeground(new java.awt.Color(164, 164, 164));
        anno1.setText("Anno");
        anno1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                anno1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                anno1FocusLost(evt);
            }
        });

        jLabel5.setText("jLabel5");

        jLabel8.setText("Descrizione sport");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numPartecipanti, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addGap(44, 44, 44)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(giorno, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mese, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anno, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IdTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(giorno1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mese1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(anno1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inserisciTorneo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(scegliCampi)))
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IdTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(giorno1)
                        .addComponent(mese1)
                        .addComponent(anno1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(giorno)
                        .addComponent(mese)
                        .addComponent(anno)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(numPartecipanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(scegliCampi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inserisciTorneo)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTorneoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTorneoActionPerformed

    private void inserisciTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserisciTorneoActionPerformed
        if(prezzo.getText().length()!=0 && anno.getText().length()!=0 && anno1.getText().length()!=0 
        && mese.getText().length()!=0 && mese1.getText().length()!=0 && giorno.getText().length()!=0
        && giorno1.getText().length()!=0){
            try {
                // TODO add your handling code here:
                LocalDate dataIn=LocalDate.of(Integer.parseInt(anno.getText()), Integer.parseInt(mese.getText()), Integer.parseInt(giorno.getText()));
                LocalDate dataFi=LocalDate.of(Integer.parseInt(anno1.getText()), Integer.parseInt(mese1.getText()), Integer.parseInt(giorno1.getText()));
                sportPlanner.inserisciNuovoTorneo(jTextField1.getText(), IdTorneo.getText(),dataIn, dataFi, Integer.parseInt(numPartecipanti.getSelectedItem().toString()),Integer.parseInt(prezzo.getText()));
                inserisciTorneo.setEnabled(false);
                scegliCampi.setEnabled(true);
                jLabel5.setVisible(false);
            }
            catch(NumberFormatException ex){
                jLabel5.setForeground(Color.red);
                jLabel5.setVisible(true);    
                jLabel5.setText("Inserisci correttamente le date!");  
            }
            catch (Exception ex) {
                jLabel5.setForeground(Color.red);
                jLabel5.setVisible(true);    
                jLabel5.setText(ex.getMessage());
            }
        }
        else{
            jLabel5.setForeground(Color.red);
            jLabel5.setVisible(true);    
            jLabel5.setText("Compilare tutti i campi!");
        }
            
    }//GEN-LAST:event_inserisciTorneoActionPerformed

    private void numPartecipantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPartecipantiActionPerformed
        // TODO add your handling code here:ù
    }//GEN-LAST:event_numPartecipantiActionPerformed

    private void scegliCampiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scegliCampiActionPerformed
        // TODO add your handling code here:
        new ScegliCampiGUI(this.sportPlanner);
        setVisible(false);
    }//GEN-LAST:event_scegliCampiActionPerformed

    private void giornoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_giornoFocusGained
        // TODO add your handling code here:
        focusGained(evt.getSource());
    }//GEN-LAST:event_giornoFocusGained

    private void giornoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_giornoFocusLost
        // TODO add your handling code here:
        focusLost(evt.getSource(), "Giorno");
    }//GEN-LAST:event_giornoFocusLost

    private void meseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_meseFocusGained
        // TODO add your handling code here:
        focusGained(evt.getSource());
    }//GEN-LAST:event_meseFocusGained

    private void meseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_meseFocusLost
        // TODO add your handling code here:
        focusLost(evt.getSource(), "Mese");
    }//GEN-LAST:event_meseFocusLost

    private void annoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_annoFocusGained
        // TODO add your handling code here:
        focusGained(evt.getSource());

    }//GEN-LAST:event_annoFocusGained

    private void annoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_annoFocusLost
        // TODO add your handling code here:
        focusLost(evt.getSource(), "Anno");

    }//GEN-LAST:event_annoFocusLost

    private void giorno1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_giorno1FocusGained
        // TODO add your handling code here:
        focusGained(evt.getSource());
    }//GEN-LAST:event_giorno1FocusGained

    private void mese1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mese1FocusLost
        // TODO add your handling code here:
        focusLost(evt.getSource(), "Mese");
    }//GEN-LAST:event_mese1FocusLost

    private void giorno1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_giorno1FocusLost
        // TODO add your handling code here:
        focusLost(evt.getSource(), "Giorno");
    }//GEN-LAST:event_giorno1FocusLost

    private void mese1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mese1FocusGained
        // TODO add your handling code here:
        focusGained(evt.getSource());
    }//GEN-LAST:event_mese1FocusGained

    private void anno1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anno1FocusGained
        // TODO add your handling code here:
        focusGained(evt.getSource());
        
    }//GEN-LAST:event_anno1FocusGained

    private void anno1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anno1FocusLost
        // TODO add your handling code here:
        focusLost(evt.getSource(), "Anno");
    }//GEN-LAST:event_anno1FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    private void focusGained(Object o){
        JTextField aux = (JTextField) o;
         if(aux.getText().equals("Giorno") || aux.getText().equals("Mese") || aux.getText().equals("Anno")){
            aux.setText("");
            aux.setForeground(new Color(0, 0, 0));
        }
    }
    
    private void focusLost(Object o, String text){
        JTextField aux = (JTextField) o;
         if(aux.getText().equals("")){
            aux.setForeground(new Color(164, 164, 164));
            aux.setText(text);
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdTorneo;
    private javax.swing.JTextField anno;
    private javax.swing.JTextField anno1;
    private javax.swing.JTextField giorno;
    private javax.swing.JTextField giorno1;
    private javax.swing.JButton inserisciTorneo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mese;
    private javax.swing.JTextField mese1;
    private javax.swing.JComboBox<String> numPartecipanti;
    private javax.swing.JTextField prezzo;
    private javax.swing.JButton scegliCampi;
    // End of variables declaration//GEN-END:variables

}
